### ISSUE TITLE
Feature request: Možnost nahrát obrázek ručně, pro použítí v šabloně.

### ISSUE THREAD

**Issue by mattez** [atk14/PupiqClient#2]
Ahooj @yarri, ahoj @mysutka ...

Bylo by super :boom: mít nějakou možnost nahrát obrázek do Pupiqa "ručně" a pak použít funkcí Pupiqa (scale, crop,..). Nechat od Pupoiqa vygenerovat URL obrázku, kterou pak použiji v šabloně.

**Moje aktuální issue:**

V šabloně zobrazuji to samé logo, v patičce malinké, v hlavičce velké. Teď pro jejich zobrazení používám jeden velký soubor odpovídající velikosti loga v hlavičce. V hlavičce je zobrazen na 100%, v patičce natvrdo nadefinuji velikost cca 30%.
Google PageSpeed test na mě řve červeně, že bych mohl u malého loga ušetřit 70% velikosti souboru. A má pravdu.
Nyní tedy musím v Gimpu vytvořit ještě malou variantu loga a budu mít dvě, malou a velkou.
Kdybych mohl poslat velké logo na Pupiq, malé bych si nechal od něj vyrobit :+1: 

**Moje představa jak by mohlo fungovat:**

1) Přihlásím se (podobně jako na Orbit41),
2) nahrát file,
3) když je to obrázek,
4) udělej mi link,
5) zadám parametry "80x80xcrop" nebo "x30" atd.. ,
6) on mi zobrazí URL,
7) u si copy/paste použiji v šaboně.

Nebo nějak tak. :]

**Comment by yarri** [comment]
Je možné se v prohlížeči přihlásit do Pupiqa a přes příslušnou API funkci nahrát obrázek.

Zde se přihlašuje:
http://i.pupiq.net/api/cs/logins/create_new/

Zde se nahrává obrázek:
http://i.pupiq.net/api/cs/images/create_new/

Po nahrání obrázku si jednoduše zkopíruješ do šablony URL, které mu Pupiq přidělí.

Pro doplnění zde je seznam všech API funkcí:
http://i.pupiq.net/api/
